name: .NET

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore TuSolucion.sln

      - name: Build
        run: dotnet build TuSolucion.sln --no-restore

      - name: Test
        run: dotnet test test1.sln --no-build --no-restore
